# Generated by Django 5.0.7 on 2024-07-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('imageUrl', models.URLField(max_length=500)),
                ('storeId', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.PROTECT, related_name='billboards', to='store.store')),
            ],
        ),
    ]
