# Generated by Django 5.0.7 on 2024-07-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('storeId', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='store.store')),
            ],
        ),
    ]
