# Generated by Django 5.0.7 on 2024-07-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('storeId', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('isFeatured', models.BooleanField(default=False)),
                ('isArchived', models.BooleanField(default=False)),
                ('categoryId', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
                ('colorId', models.ForeignKey(db_column='colorId', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.color')),
                ('sizeId', models.ForeignKey(db_column='sizeId', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.size')),
                ('storeId', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('orderId', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.order')),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=400)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.PROTECT, related_name='image', to='store.product')),
            ],
        ),
    ]
