# Generated by Django 5.0.7 on 2024-07-23 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_product_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='store.product'),
        ),
    ]
